In [1]:
import numpy as np

In [4]:
arr1 = np.array([1, 2, 3, 6, 8, 10, 32, 65, 89, 100])

In [5]:
arr1

array([  1,   2,   3,   6,   8,  10,  32,  65,  89, 100])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.shape

(10,)

In [12]:
arr2 = np.array([[1, 2, 3, 5], [2, 4, 5, 6], [10, 7, 8, 9]])

In [13]:
type(arr2)

numpy.ndarray

In [14]:
arr2

array([[ 1,  2,  3,  5],
       [ 2,  4,  5,  6],
       [10,  7,  8,  9]])

In [15]:
arr2.shape

(3, 4)

In [16]:
arr1.size

10

In [17]:
arr2.size

12

# 균일한 값으로 생성

In [18]:
array1 = np.full(6, 7)
    
print(array1)

[7 7 7 7 7 7]


# 모든 값이 0인 numpy array 생성

In [19]:
array1 = np.full(6, 0)
array2 = np.zeros(6, dtype=int)
    
print(array1)
print()
print(array2)

[0 0 0 0 0 0]

[0 0 0 0 0 0]


# 랜덤한 값들로 생성

In [23]:
array1 = np.random.random(6)
array2 = np.random.random(6)
    
print(array1)
print()
print(array2)

[0.76907246 0.26542591 0.35577821 0.86621607 0.67323174 0.32683805]

[0.34521153 0.5668681  0.72370762 0.20730542 0.31613836 0.67359367]


# 연속된 값들이 담긴 numpy array 생성

In [25]:
# 0부터 m-1까지의 수를 원소로 갖는 배열 생성

array1 = np.arange(6)
print(array1)

[0 1 2 3 4 5]


In [26]:
# 2부터 m-1까지의 수를 원소로 갖는 배열 생성

array1 = np.arange(2, 7)
print(array1)

[2 3 4 5 6]


In [27]:
# n부터 m-1까지의 수를 s간격으로 원소로 갖는 배열 생성

array1 = np.arange(3, 17, 3)
print(array1)

[ 3  6  9 12 15]


In [28]:
arr1 = np.array([1, 2, 3, 6, 8, 10, 32, 65, 89, 100])

In [29]:
arr1[0]

np.int64(1)

In [32]:
arr2 = np.array([1, 3, 5])

In [33]:
arr1[arr2]

array([ 2,  6, 10])

In [34]:
arr1[:10]

array([  1,   2,   3,   6,   8,  10,  32,  65,  89, 100])

In [35]:
arr1[3:8]

array([ 6,  8, 10, 32, 65])

In [38]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]
won_array = np.array(revenue_in_yen) * 10.08
# 여기에 코드를 작성하세요

# 테스트 코드
won_array

array([3024000., 3427200., 3225600., 3628800., 4435200., 1411200.,
       1814400., 3427200., 3326400., 2923200., 2822400., 3830400.,
       1713600., 1411200., 2318400., 3931200., 4032000., 3528000.,
       3830400., 1512000., 1108800., 2419200., 3830400., 3830400.,
       3427200., 4233600., 1512000., 1310400., 3628800., 3225600.,
       2520000.])

In [ ]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

revenue_in_dollar = [
    1200, 1600, 1400, 1300, 
    2100, 1400, 1500, 2100, 
    1500, 1500, 2300, 2100, 
    2800, 2600, 1700, 1400, 
    2100, 2300, 1600, 1800, 
    2200, 2400, 2100, 2800, 
    1900, 2100, 1800, 2200, 
    2100, 1600, 1800
]

won_array = np.array(revenue_in_yen) * 10.08 + np.array(revenue_in_dollar) * 1138

# 테스트 코드
won_array

In [49]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

# 여기에 코드를 작성하세요
bad_days_revenue = np.array(revenue_in_yen)
filter = np.where(bad_days_revenue < 200000)

bad_days_revenue = bad_days_revenue[filter]
# 테스트 코드
bad_days_revenue

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])